In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('iris_prep.csv')

In [3]:
data.head()

   sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [4]:
data.drop(data[data.species==2].index).species.unique()

array([0, 1], dtype=int64)

In [5]:
data = data.drop(data[data.species==2].index)

In [6]:
import numpy as np

In [7]:
x,y = data.drop(['species'], axis=1), data['species']
x = x.values
y = y.values.reshape(-1,1)
print(x.shape)
print(y.shape)

(100, 4)
(100, 1)

In [8]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3]])

In [9]:
y

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]], dtype=int64)

In [10]:
class Perceptron :
    def __init__(self, input_dim, output_dim, lr, classes):
        self.inp = input_dim
        self.out = output_dim
        self.w = np.random.rand(self.inp,self.out)
        self.b = np.random.rand(self.out)
        self.lr = lr
        self.c = classes
        
    def sigmoid(self, x):
        return 1/(1+np.exp(-x))
    
    def sigmoid_derivative(self,x):
        return self.sigmoid(x)*(1-self.sigmoid(x))
    
    def train(self, x, y):
        mul = np.apply_along_axis(lambda i : np.dot(i,self.w)+self.b , 1, x) 
        sig = self.sigmoid(mul)*self.c
        err = (sig-y)**2
        
        loss = err.sum()
        
        dE_da = sig-y
        da_do = self.sigmoid_derivative(mul)
        dE_dw = np.dot(x.T, dE_da*da_do)
        
        self.w = self.w - self.lr*dE_dw 
        for i in dE_da*da_do:
            self.b -= i
        return loss
    
    def fit(self, x, y, epochs=1000, printCost = False, printGap = 100):
        for i in range(epochs):
            c = self.train(x,y)
            if printCost and i%printGap==0:
                print("Epoch",i,"\t Cost: ",c)
    
    def predict(self, x):
        return self.sigmoid(np.dot(x,self.w)+self.b)

In [11]:
p = Perceptron(4,1, 0.01, 1)
p.fit(x,y,10000,True,1000)

Epoch 0 	 Cost:  49.178143602648916
Epoch 1000 	 Cost:  0.05131905450668943
Epoch 2000 	 Cost:  0.027394511545472355
Epoch 3000 	 Cost:  0.01875893077503431
Epoch 4000 	 Cost:  0.014291088024507449
Epoch 5000 	 Cost:  0.011555689025779288
Epoch 6000 	 Cost:  0.009706766359898063
Epoch 7000 	 Cost:  0.008372523749899594
Epoch 8000 	 Cost:  0.00736378791467395
Epoch 9000 	 Cost:  0.006574080344319951

In [12]:
def conv(x):
    if x<0.5:
        return 0
    return 1

In [13]:
# Random check
n = 20
nums = np.random.randint(0, 100, 20)
ls = []
for i in sorted(nums):
    ls.append([i, conv(p.predict(x[i])), y[i][0]])

d = pd.DataFrame(ls, columns=['index', 'predicted', 'actual'])
d

    index  predicted  actual
0       4          0       0
1       4          0       0
2       7          0       0
3       9          0       0
4      20          0       0
5      21          0       0
6      32          0       0
7      32          0       0
8      37          0       0
9      43          0       0
10     49          0       0
11     68          1       1
12     72          1       1
13     73          1       1
14     73          1       1
15     73          1       1
16     74          1       1
17     75          1       1
18     89          1       1
19     98          1       1

In [14]:
# Full check
c = 0
n = 100
for i in range(n):
    if conv(p.predict(x[i]))==y[i][0]:
        c += 1

print("Accuracy : ",c/n)

Accuracy :  1.0